name: Build and Push Python Frontend

on:
  pull_request:
    branches:
      - main

permissions:
  packages: read
  contents: write
  security-events: write
  statuses: write
  checks: write
  id-token: write
  actions: read

jobs:
  build:
    uses: UKHSA-Internal/devops-github-reusable-workflows/.github/workflows/container-image-build.yml@feature/doe-150-reusable-container-build
    with:
      release_after_build: true
      image_name: hello-world-frontend